//  getters types
export const DONE_MENT_TITLE = 'DONE_MENT_TITLE'
export const DONE_RESULT_VALUE = 'DONE_RESULT_VALUE'
export const DONE_OLD_VALUE = 'DONE_OLD_VALUE'
export const DONE_NEW_VALUE = 'DONE_NEW_VALUE'
export const DONE_PROCESS_STR = 'DONE_PROCESS_STR'
export const DONE_RESULT_STR = 'DONE_RESULT_STR'
export const DONE_TEMP_VALUE = 'DONE_TEMP_VALUE'
export const DONE_ARITHMETIC_SYMBOL = 'DONE_ARITHMETIC_SYMBOL'
export const DONE_ISCHANGE_RESULT_VALUE = 'DONE_ISCHANGE_RESULT_VALUE'
export const DONE_ISCHANGE_PROCESS_STR = 'DONE_ISCHANGE_PROCESS_STR'
export const DONE_ISCANRUN = 'DONE_ISCANRUN'
export const DONE_RESULT_HISTORY_ARR = 'DONE_RESULT_HISTORY_ARR'

// mutation types,
export const TOGGLE_MENT_TITLE = 'TOGGLE_MENT_TITLE'
export const TOGGLE_RESULT_VALUE = 'TOGGLE_RESULT_VALUE'
export const TOGGLE_OLD_VALUE = 'TOGGLE_OLD_VALUE'
export const TOGGLE_NEW_VALUE = 'TOGGLE_NEW_VALUE'
export const TOGGLE_PROCESS_STR = 'TOGGLE_PROCESS_STR'
export const TOGGLE_RESULT_STR = 'TOGGLE_RESULT_STR'
export const TOGGLE_TEMP_VALUE = 'TOGGLE_TEMP_VALUE'
export const TOGGLE_ARITHMETIC_SYMBOL = 'TOGGLE_ARITHMETIC_SYMBOL'
export const TOGGLE_ISCHANGE_RESULT_VALUE = 'TOGGLE_ISCHANGE_RESULT_VALUE'
export const TOGGLE_ISCHANGE_PROCESS_STR = 'TOGGLE_ISCHANGE_PROCESS_STR'
export const TOGGLE_ISCANRUN = 'TOGGLE_ISCANRUN'
export const TOGGLE_RESULT_HISTORY_ARR = 'TOGGLE_RESULT_HISTORY_ARR'

// actions types no actions
